[package]
name = "catalyst"
version = "0.1.0"
authors = ["technetos <mrgould93@gmail.com>"]
edition = "2018"
license = "Apache-2.0"
description = "Nothing to see here yet."

[dependencies]
hyper = "0.12"
futures = "0.1"
serde = "1.0.82"
serde_json = "1.0"
futures-cpupool = "0.1.8"
