[package]
name = "router-macro"
version = "0.1.0"
authors = ["technetos <mrgould93@gmail.com>"]
edition = "2018"

[dependencies]
syn = { version = "0.15.23", features = ["extra-traits", "parsing"]}
quote = "0.6.8"
proc-macro2 = "0.4.20"
heck = "0.3.1"

[lib]
proc-macro = true
